namespace:
  name: sandbox

service:
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

image:
  repository: chrisking99/techtrends
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: 250m
    mem: 64mi
  limits:
    cpu: 500m
    mem: 128mi

containerPort: 3111

livenessProbe:
  path: /healthz

readinessProbe:
  path: /healthz